//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpleadoConsulta.ServicioDeConsulta {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/AplicacionDeServicios")]
    [System.SerializableAttribute()]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpleadoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LegajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpleadoId {
            get {
                return this.EmpleadoIdField;
            }
            set {
                if ((this.EmpleadoIdField.Equals(value) != true)) {
                    this.EmpleadoIdField = value;
                    this.RaisePropertyChanged("EmpleadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Legajo {
            get {
                return this.LegajoField;
            }
            set {
                if ((this.LegajoField.Equals(value) != true)) {
                    this.LegajoField = value;
                    this.RaisePropertyChanged("Legajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioDeConsulta.IServicioConsulta")]
    public interface IServicioConsulta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorId", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorIdResponse")]
        EmpleadoConsulta.ServicioDeConsulta.Empleado BuscarPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorId", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorIdResponse")]
        System.Threading.Tasks.Task<EmpleadoConsulta.ServicioDeConsulta.Empleado> BuscarPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorNombre", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorNombreResponse")]
        EmpleadoConsulta.ServicioDeConsulta.Empleado[] BuscarPorNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorNombre", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorNombreResponse")]
        System.Threading.Tasks.Task<EmpleadoConsulta.ServicioDeConsulta.Empleado[]> BuscarPorNombreAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorLegajo", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorLegajoResponse")]
        EmpleadoConsulta.ServicioDeConsulta.Empleado[] BuscarPorLegajo(string legajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorLegajo", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorLegajoResponse")]
        System.Threading.Tasks.Task<EmpleadoConsulta.ServicioDeConsulta.Empleado[]> BuscarPorLegajoAsync(string legajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorDNI", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorDNIResponse")]
        EmpleadoConsulta.ServicioDeConsulta.Empleado[] BuscarPorDNI(string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorDNI", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorDNIResponse")]
        System.Threading.Tasks.Task<EmpleadoConsulta.ServicioDeConsulta.Empleado[]> BuscarPorDNIAsync(string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorApellido", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorApellidoResponse")]
        EmpleadoConsulta.ServicioDeConsulta.Empleado[] BuscarPorApellido(string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorApellido", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorApellidoResponse")]
        System.Threading.Tasks.Task<EmpleadoConsulta.ServicioDeConsulta.Empleado[]> BuscarPorApellidoAsync(string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/Todos", ReplyAction="http://tempuri.org/IServicioConsulta/TodosResponse")]
        EmpleadoConsulta.ServicioDeConsulta.Empleado[] Todos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/Todos", ReplyAction="http://tempuri.org/IServicioConsulta/TodosResponse")]
        System.Threading.Tasks.Task<EmpleadoConsulta.ServicioDeConsulta.Empleado[]> TodosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioConsultaChannel : EmpleadoConsulta.ServicioDeConsulta.IServicioConsulta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioConsultaClient : System.ServiceModel.ClientBase<EmpleadoConsulta.ServicioDeConsulta.IServicioConsulta>, EmpleadoConsulta.ServicioDeConsulta.IServicioConsulta {
        
        public ServicioConsultaClient() {
        }
        
        public ServicioConsultaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioConsultaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EmpleadoConsulta.ServicioDeConsulta.Empleado BuscarPorId(int id) {
            return base.Channel.BuscarPorId(id);
        }
        
        public System.Threading.Tasks.Task<EmpleadoConsulta.ServicioDeConsulta.Empleado> BuscarPorIdAsync(int id) {
            return base.Channel.BuscarPorIdAsync(id);
        }
        
        public EmpleadoConsulta.ServicioDeConsulta.Empleado[] BuscarPorNombre(string nombre) {
            return base.Channel.BuscarPorNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<EmpleadoConsulta.ServicioDeConsulta.Empleado[]> BuscarPorNombreAsync(string nombre) {
            return base.Channel.BuscarPorNombreAsync(nombre);
        }
        
        public EmpleadoConsulta.ServicioDeConsulta.Empleado[] BuscarPorLegajo(string legajo) {
            return base.Channel.BuscarPorLegajo(legajo);
        }
        
        public System.Threading.Tasks.Task<EmpleadoConsulta.ServicioDeConsulta.Empleado[]> BuscarPorLegajoAsync(string legajo) {
            return base.Channel.BuscarPorLegajoAsync(legajo);
        }
        
        public EmpleadoConsulta.ServicioDeConsulta.Empleado[] BuscarPorDNI(string DNI) {
            return base.Channel.BuscarPorDNI(DNI);
        }
        
        public System.Threading.Tasks.Task<EmpleadoConsulta.ServicioDeConsulta.Empleado[]> BuscarPorDNIAsync(string DNI) {
            return base.Channel.BuscarPorDNIAsync(DNI);
        }
        
        public EmpleadoConsulta.ServicioDeConsulta.Empleado[] BuscarPorApellido(string apellido) {
            return base.Channel.BuscarPorApellido(apellido);
        }
        
        public System.Threading.Tasks.Task<EmpleadoConsulta.ServicioDeConsulta.Empleado[]> BuscarPorApellidoAsync(string apellido) {
            return base.Channel.BuscarPorApellidoAsync(apellido);
        }
        
        public EmpleadoConsulta.ServicioDeConsulta.Empleado[] Todos() {
            return base.Channel.Todos();
        }
        
        public System.Threading.Tasks.Task<EmpleadoConsulta.ServicioDeConsulta.Empleado[]> TodosAsync() {
            return base.Channel.TodosAsync();
        }
    }
}
